'use client';
import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type LanguageCode = 'en' | 'id' | 'jv' | 'su' | 'th' | 'zh' | 'ko';

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const dictionaries: Record<LanguageCode, Record<string, string>> = {
  en: {
    'bot_engine': 'Bot Engine',
    'uptime': 'Uptime',
    'system_processes': 'System Processes',
    'running': 'Running',
    'idle': 'Idle',
    'waiting': 'Waiting',
    'status_active': 'Active',
    'status_disabled': 'Disabled',
    'trigger_syntax': 'Trigger Syntax',
    'trigger_placeholder': 'e.g., !save',
    'action_output': 'Action Output',
    'save_media_cloud': 'Save Media to Cloud',
    'auto_forward': 'Auto Forward',
    'trigger_webhook': 'Trigger Webhook',
    'active_groups': 'Active Groups',
    'autosave': 'Autosave',
    'applying_changes': 'Applying changes...',
    'storage': 'Storage',

    'uploading': 'Uploading...',
    'upload_file': 'Upload File',
    'your_files': 'Your Files',
    'no_files_uploaded_yet': 'No files uploaded yet',
    'hold_on_changes': 'Hold on, you changed something.',

    'version_info': 'v0.3 beta alpha',
    'macros_builder': 'Macros Builder',
    'desc_macros_builder': 'Create advanced custom commands and cloud storage hooks.',
    'minigames': 'Minigames',
    'desc_minigames': 'Interactive games like Werewolf and Truth or Dare for groups.',
    'ai_persona': 'AI Persona Studio',
    'desc_ai_persona': 'Custom AI Personalities for WhatsApp.',
    'broadcast_manager': 'Broadcast Manager',
    'desc_broadcast_manager': 'Schedule bulk messages and campaigns.',
    'analytics_insights': 'Analytics & Insights',
    'desc_analytics_insights': 'Bot statistics and usage metrics.',
    'ticketing_system': 'Live Ticketing System',
    'desc_ticketing_system': 'Human handoff and support inbox for bot users.',
    'app_integrations': 'App Integrations',
    'desc_app_integrations': 'Connect with Webhooks, Google Sheets, Discord & Slack.',

    'dashboard': 'Dashboard',
    'swap': 'Swap',
    'earn': 'Earn',
    'new': 'NEW',
    'settings': 'Settings',
    'language': 'Language',
    'appearance': 'Appearance',
    'theme': 'Theme',
    'task_manager': 'Task Manager',
    'monitor_processes': 'Monitor open windows & processes',
    'subscription': 'Subscription',
    'extend_plan': 'Extend your subscription plan',
    'log_out': 'Log out',
    'sign_out': 'Sign out of your session',
    'app_store': 'App Store',
    'discover_modules': 'Discover and install powerful modules for your OS.',
    'loading_catalog': 'Loading catalog...',
    'released': 'Released',
    'installed': 'Installed',
    'get_install': 'Get / Install',
    'installing': 'Installing...',
    'pinned_apps': 'PINNED APPS',
    'menu': 'MENU',
    'services_pricing': 'Services & Pricing',
    'subscription_desc': 'Wazle Subscription Plans',
    'budget_adjustment_title': 'Want to adjust limits to your budget?',
    'budget_adjustment_btn': 'Budget Adjustment',
    'adjust_package': 'Adjust Package',
    'response_slot': 'Response Slots',
    'whatsapp_group': 'WhatsApp Groups',
    'support_service': 'Support Service',
    'basic_service': 'Basic Service',
    'service_247': '24/7 Service',
    'total_estimation': 'Total Estimation',
    'order_via_wa': 'Order via WA',
    'storage_note': 'Storage / Cloud Storage will not be increased / adjusted by this service',
    'per_month': '/mo',
    'plan_free_name': 'Free',
    'plan_basic_name': 'Basic',
    'plan_standard_name': 'Standard',
    'plan_premium_name': 'Premium',
    'feat_1_resp': '1 Response',
    'feat_5_resp': '5 Responses',
    'feat_25_resp': '25 Responses',
    'feat_100_resp': '100 Responses',
    'feat_no_upload': 'No File Upload',
    'feat_500kb_upload': '500kb per file upload',
    'feat_5mb_upload': '5MB per file upload',
    'feat_15mb_upload': '15MB per file upload',
    'feat_few_services': 'Few Services',
    'feat_50mb_storage': '50MB Max Storage',
    'feat_500mb_storage': '500MB Max Storage',
    'feat_1000mb_storage': '1000MB Max Storage',
    'feat_1_group': '1 Group',
    'feat_2_group': '2 Groups',
    'feat_5_group': '5 Groups',
    'feat_basic_support': 'Basic Support',
    'feat_247_support': '24/7 Support',
    'current_subscription': 'Current Subscription',
    'plan': 'Plan',
    'days_left': 'Days Left',
    'status': 'Status',
    'available_plans': 'Available Plans',
    'popular': 'Popular',
    'days': 'days',
    'Active': 'Active',
    'Inactive': 'Inactive',
    'Free': 'Free',
    'Basic': 'Basic',
    'Standard': 'Standard',
    'Premium': 'Premium',
    'hi': 'HI',
    'plan_active': 'Plan Active',
    'profile_information': 'Profile Information',
    'user_id': 'User ID',
    'connected_whatsapp': 'Connected WhatsApp',
    'valid_until': 'Valid Until',
    'protocols': 'Protocols',
    'access_modules': 'Access all your installed modules',
    'control_center': 'Control Center',
    'desc_control_center': 'Bot configuration & logic',
    'file_explorer': 'File Explorer',
    'desc_file_explorer': 'Manage bot storage',
    'desc_task_manager': 'Monitor system resources',
    'group_manager': 'Group Manager',
    'desc_group_manager': 'Manage connected groups',
    'auto_responders': 'Auto Responders',
    'used': 'used',
    'create_new_response': 'Create New Response',
    'keyword_label': 'Keyword',
    'example_ping': 'Example: ping',
    'match_type_label': 'Match Type',
    'exact': 'Exact',
    'contains': 'Contains',
    'bot_reply_label': 'Bot Reply',
    'example_pong': 'Example: pong!',
    'saving': 'Saving...',
    'save_auto_response': 'Save Auto Response',
    'no_auto_responders': 'No auto responders yet.',
    'delete': 'Delete',
    'group_links': 'Group Links',
    'your_tier_is': 'Your tier is',
    'max': 'Max',
    'groups_lowercase': 'groups',
    'whatsapp_group_prefix': 'WhatsApp Group',
    'clear_link': 'Clear Link',
    'contact_staff_lock': 'Contact Wazle staff to change this link.',
    'locked': 'Locked',
    'save_links': 'Save Links',
    'server_reset': 'Server reset',
    'subscription_warning': 'Warning: Your subscription has only {days} days left!',
    'focus_music': 'Focus Music',
    'play': 'Play',
    'pause': 'Pause',
    'nav_home': 'Home',
    'nav_pricing': 'Pricing',
    'nav_download': 'Download',
    'pricing_title': 'Pricing',
    'pricing_subtitle': 'Find the perfect plan to scale your business.',
    'plan_free_desc': 'For creators taking their first steps with automation systems.',
    'plan_basic_desc': 'For freelancers and small businesses needing more freedom.',
    'plan_standard_desc': 'Complete solution for team operations and online stores.',
    'plan_premium_desc': 'Designed for agencies, studios, and large-scale businesses.',
    'btn_choose_free': 'Choose Free',
    'btn_choose_basic': 'Choose Basic',
    'btn_choose_standard': 'Choose Standard',
    'btn_choose_premium': 'Choose Premium',
    'custom_billing_title': 'Custom Billing',
    'custom_billing_desc': 'Need custom limits, enterprise ERP integration, or on-premise security? We can build a system architecture tailored to your specific needs.',
    'btn_contact_wa': 'Contact Us via WhatsApp',
    'footer_storage_note': 'Note: The storage capacity above only applies to media uploads (images/documents). WhatsApp text messages do not consume storage space.',
    'download_title': 'Wazle App',
    'download_subtitle': 'Get the best experience and complete features with our native Android app.',
    'download_btn': 'Download APK',
    'download_preparing': 'Preparing...',
    'download_version': 'Version: Beta v0.2 • Size: 6MB',
    'download_note': 'Note: Please free up at least 30MB of storage space.',
    'toast_welcome_saved': 'Welcome template saved successfully!',
    'toast_settings_updated': 'Settings for {label} updated!',
    'toast_file_uploaded': 'File uploaded successfully!',
    'toast_file_deleted': 'File deleted successfully!',
    'toast_group_saved': 'Group data saved successfully!',
    'toast_group_save_failed': 'Failed to save. Ensure Localtunnel bypass is done.',
    'toast_responder_updated': 'Responder updated successfully!',
    'toast_responder_added': 'Responder added successfully!',
    'toast_responder_deleted': 'Responder deleted successfully!',
    'toast_responder_failed': 'Failed to save responder.',
    'engine_status': 'Engine Status',
    'connecting': 'Connecting...',
    'offline': 'Offline',
    'start': 'Start',
    'stop': 'Stop',
    'scan_qr_desc': 'Scan this QR Code using<br/>WhatsApp on target phone',
    'configurations': 'Configurations',
    'anti_link': 'Anti-Link',
    'anti_link_desc': 'Automatically delete links in groups',
    'welcome_msg': 'Welcome Msg',
    'welcome_msg_desc': 'Greet new members automatically',
    'welcome_message': 'Welcome Message',
    'premium_feature': 'Premium Feature',
    'upgrade_custom_welcome': 'Upgrade plan to customize welcome message.',
    'welcome_placeholder': 'Hello, welcome to the group...',
    'save_text': 'Save Text'
  },
  id: {
    'bot_engine': 'Mesin Bot',
    'uptime': 'Waktu Aktif',
    'system_processes': 'Proses Sistem',
    'running': 'Berjalan',
    'idle': 'Diam',
    'waiting': 'Menunggu',
    'status_active': 'Aktif',
    'status_disabled': 'Dinonaktifkan',
    'trigger_syntax': 'Sintaks Pemicu',
    'trigger_placeholder': 'misal: !simpan',
    'action_output': 'Keluaran Aksi',
    'save_media_cloud': 'Simpan Media ke Cloud',
    'auto_forward': 'Teruskan Otomatis',
    'trigger_webhook': 'Picu Webhook',
    'active_groups': 'Grup Aktif',
    'autosave': 'Simpan Otomatis',
    'applying_changes': 'Menerapkan perubahan...',
    'storage': 'Penyimpanan',

    'uploading': 'Mengunggah...',
    'upload_file': 'Unggah File',
    'your_files': 'File Anda',
    'no_files_uploaded_yet': 'Belum ada file yang diunggah',
    'hold_on_changes': 'Tunggu, Anda mengubah sesuatu.',

    'version_info': 'v0.3 beta alpha',
    'macros_builder': 'Pembuat Makro',
    'desc_macros_builder': 'Buat perintah kustom tingkat lanjut dan pemicu penyimpanan cloud.',
    'minigames': 'Mini-game',
    'desc_minigames': 'Game interaktif seperti Werewolf dan Truth or Dare untuk grup.',
    'ai_persona': 'Studio Persona AI',
    'desc_ai_persona': 'Kepribadian AI Kustom untuk WhatsApp.',
    'broadcast_manager': 'Manajer Siaran',
    'desc_broadcast_manager': 'Jadwalkan pesan massal dan kampanye.',
    'analytics_insights': 'Analisis & Wawasan',
    'desc_analytics_insights': 'Statistik bot dan metrik penggunaan.',
    'ticketing_system': 'Sistem Tiket Langsung',
    'desc_ticketing_system': 'Peralihan ke manusia dan kotak masuk dukungan untuk pengguna.',
    'app_integrations': 'Integrasi Aplikasi',
    'desc_app_integrations': 'Hubungkan dengan Webhook, Google Sheets, Discord & Slack.',

    'dashboard': 'Dasbor',
    'swap': 'Tukar',
    'earn': 'Hasil',
    'new': 'BARU',
    'settings': 'Pengaturan',
    'language': 'Bahasa',
    'appearance': 'Tampilan',
    'theme': 'Tema',
    'task_manager': 'Manajer Tugas',
    'monitor_processes': 'Pantau proses & jendela terbuka',
    'subscription': 'Perpanjang Langganan',
    'extend_plan': 'Perpanjang paket langganan kamu',
    'log_out': 'Keluar',
    'sign_out': 'Keluar dari sesi kamu',
    'app_store': 'Toko Aplikasi',
    'discover_modules': 'Temukan dan pasang modul hebat untuk OS kamu.',
    'loading_catalog': 'Memuat katalog...',
    'released': 'Dirilis',
    'installed': 'Terpasang',
    'get_install': 'Pasang',
    'installing': 'Memasang...',
    'pinned_apps': 'APLIKASI TERSEMAT',
    'menu': 'MENU',
    'services_pricing': 'Layanan & Pricing',
    'subscription_desc': 'Paket Langganan Wazle',
    'budget_adjustment_title': 'Ingin menyesuaikan limit sesuai budget Anda?',
    'budget_adjustment_btn': 'Penyesuaian Anggaran',
    'adjust_package': 'Sesuaikan Paket',
    'response_slot': 'Slot Respon',
    'whatsapp_group': 'Grup WhatsApp',
    'support_service': 'Layanan Bantuan',
    'basic_service': 'Layanan Dasar',
    'service_247': 'Layanan 24/7',
    'total_estimation': 'Total Estimasi',
    'order_via_wa': 'Pesan via WA',
    'storage_note': 'Penyimpanan / Cloud Storage tidak akan ditambah / menyesuaikan layanan',
    'per_month': '/bln',
    'plan_free_name': 'Gratis',
    'plan_basic_name': 'Dasar',
    'plan_standard_name': 'Standar',
    'plan_premium_name': 'Premium',
    'feat_1_resp': '1 Respon',
    'feat_5_resp': '5 Respon',
    'feat_25_resp': '25 Respon',
    'feat_100_resp': '100 Respon',
    'feat_no_upload': 'Tanpa Upload File',
    'feat_500kb_upload': '500kb per file upload',
    'feat_5mb_upload': '5MB per file upload',
    'feat_15mb_upload': '15MB per file upload',
    'feat_few_services': 'Layanan Terbatas',
    'feat_50mb_storage': 'Maksimal 50MB Storage',
    'feat_500mb_storage': 'Maksimal 500MB Storage',
    'feat_1000mb_storage': 'Maksimal 1000MB Storage',
    'feat_1_group': '1 Grup',
    'feat_2_group': '2 Grup',
    'feat_5_group': '5 Grup',
    'feat_basic_support': 'Dukungan Dasar',
    'feat_247_support': 'Dukungan 24/7',
    'current_subscription': 'Langganan Saat Ini',
    'plan': 'Paket',
    'days_left': 'Sisa Hari',
    'status': 'Status',
    'available_plans': 'Paket Tersedia',
    'popular': 'Populer',
    'days': 'hari',
    'Active': 'Aktif',
    'Inactive': 'Tidak Aktif',
    'Free': 'Gratis',
    'Basic': 'Dasar',
    'Standard': 'Standar',
    'Premium': 'Premium',
    'hi': 'HALO',
    'plan_active': 'Paket Aktif',
    'profile_information': 'Informasi Profil',
    'user_id': 'ID Pengguna',
    'connected_whatsapp': 'WhatsApp Terhubung',
    'valid_until': 'Berlaku Hingga',
    'protocols': 'Protokol',
    'access_modules': 'Akses semua modul terpasang',
    'control_center': 'Pusat Kontrol',
    'desc_control_center': 'Konfigurasi & logika bot',
    'file_explorer': 'File Explorer',
    'desc_file_explorer': 'Kelola penyimpanan bot',
    'desc_task_manager': 'Pantau sumber daya sistem',
    'group_manager': 'Manajer Grup',
    'desc_group_manager': 'Kelola grup terhubung',
    'auto_responders': 'Auto Responder',
    'used': 'digunakan',
    'create_new_response': 'Buat Respon Baru',
    'keyword_label': 'Kata Kunci (Keyword)',
    'example_ping': 'Contoh: ping',
    'match_type_label': 'Tipe Kecocokan (Match Type)',
    'exact': 'Pasti (Exact)',
    'contains': 'Mengandung (Contains)',
    'bot_reply_label': 'Balasan Bot',
    'example_pong': 'Contoh: pong!',
    'saving': 'Menyimpan...',
    'save_auto_response': 'Simpan Auto Respon',
    'no_auto_responders': 'Belum ada auto responder.',
    'delete': 'Hapus',
    'group_links': 'Tautan Grup',
    'your_tier_is': 'Paket Anda adalah',
    'max': 'Maksimal',
    'groups_lowercase': 'grup',
    'whatsapp_group_prefix': 'Grup WhatsApp',
    'clear_link': 'Hapus Tautan',
    'contact_staff_lock': 'Hubungi staf Wazle untuk mengubah tautan ini.',
    'locked': 'Terkunci',
    'save_links': 'Simpan Tautan',
    'server_reset': 'Server di-reset',
    'subscription_warning': 'Peringatan: Langganan Anda tersisa {days} hari lagi!',
    'focus_music': 'Musik Fokus',
    'play': 'Putar',
    'pause': 'Jeda',
    'nav_home': 'Beranda',
    'nav_pricing': 'Harga',
    'nav_download': 'Unduh',
    'pricing_title': 'Harga',
    'pricing_subtitle': 'Temukan paket yang paling cocok untuk mengembangkan skala bisnis Anda.',
    'plan_free_desc': 'Untuk kreator yang baru mengambil langkah pertama dengan sistem otomatisasi.',
    'plan_basic_desc': 'Untuk freelancer dan bisnis kecil yang butuh kebebasan lebih.',
    'plan_standard_desc': 'Solusi lengkap untuk operasional tim dan toko online.',
    'plan_premium_desc': 'Didesain untuk agensi, studio, dan bisnis berskala besar.',
    'btn_choose_free': 'Pilih Gratis',
    'btn_choose_basic': 'Pilih Basic',
    'btn_choose_standard': 'Pilih Standard',
    'btn_choose_premium': 'Pilih Premium',
    'custom_billing_title': 'Custom Billing',
    'custom_billing_desc': 'Butuh limit khusus, integrasi ERP perusahaan, atau keamanan jaringan on-premise? Kami dapat menyusun arsitektur sistem sesuai kebutuhan spesifik Anda.',
    'btn_contact_wa': 'Hubungi Kami via WhatsApp',
    'footer_storage_note': 'Catatan: Kapasitas storage di atas hanya berlaku untuk unggahan media (gambar/dokumen). Data teks pesan WhatsApp tidak memakan ruang penyimpanan.',
    'download_title': 'Aplikasi Wazle',
    'download_subtitle': 'Dapatkan pengalaman terbaik dan fitur terlengkap dengan aplikasi native Android kami.',
    'download_btn': 'Unduh APK',
    'download_preparing': 'Menyiapkan...',
    'download_version': 'Versi: Beta v0.2 • Ukuran: 6MB',
    'download_note': 'Catatan: Siapkan ruang kosong setidaknya 30MB (free up at least 30MB)',
    'toast_welcome_saved': 'Template sambutan berhasil disimpan!',
    'toast_settings_updated': 'Pengaturan {label} diperbarui!',
    'toast_file_uploaded': 'File berhasil diupload!',
    'toast_file_deleted': 'File berhasil dihapus!',
    'toast_group_saved': 'Data grup berhasil disimpan!',
    'toast_group_save_failed': 'Gagal menyimpan. Pastikan Bypass Localtunnel sudah dilakukan.',
    'toast_responder_updated': 'Responder berhasil diupdate!',
    'toast_responder_added': 'Responder berhasil ditambahkan!',
    'toast_responder_deleted': 'Responder berhasil dihapus!',
    'toast_responder_failed': 'Gagal menyimpan responder.',
    'engine_status': 'Status Mesin',
    'connecting': 'Menghubungkan...',
    'offline': 'Offline',
    'start': 'Mulai',
    'stop': 'Berhenti',
    'scan_qr_desc': 'Scan QR Code ini menggunakan<br/>WhatsApp di HP target',
    'configurations': 'Konfigurasi',
    'anti_link': 'Anti-Link',
    'anti_link_desc': 'Otomatis hapus tautan di grup',
    'welcome_msg': 'Pesan Sambutan',
    'welcome_msg_desc': 'Sambut member baru otomatis',
    'welcome_message': 'Pesan Sambutan',
    'premium_feature': 'Fitur Premium',
    'upgrade_custom_welcome': 'Upgrade paket untuk kustomisasi pesan welcome.',
    'welcome_placeholder': 'Halo, selamat datang di grup...',
    'save_text': 'Simpan Teks'
  },
  jv: {
    'bot_engine': 'Mesin Bot',
    'uptime': 'Wektu Aktif',
    'system_processes': 'Proses Sistem',
    'running': 'Mlumaku',
    'idle': 'Nganggur',
    'waiting': 'Ngenteni',
    'status_active': 'Aktif',
    'status_disabled': 'Pateni',
    'trigger_syntax': 'Pemicu Sintaks',
    'trigger_placeholder': 'umpamane: !simpen',
    'action_output': 'Keluaran Aksi',
    'save_media_cloud': 'Simpen Media menyang Awan',
    'auto_forward': 'Teruske Otomatis',
    'trigger_webhook': 'Pemicu Webhook',
    'active_groups': 'Grup Aktif',
    'autosave': 'Simpen Otomatis',
    'applying_changes': 'Ngetrapake owah-owahan...',
    'storage': 'Panyimpenan',

    'uploading': 'Ngunggah...',
    'upload_file': 'Unggah File',
    'your_files': 'File Panjenengan',
    'no_files_uploaded_yet': 'Durung ana file sing diunggah',
    'hold_on_changes': 'Ngenteni, sampeyan wis ngganti soko.',

    'version_info': 'v0.3 beta alpha',
    'macros_builder': 'Nggawe Makro',
    'desc_macros_builder': 'Nggawe printah khusus lan pemicu panyimpenan awan.',
    'minigames': 'Dolanan Mini',
    'desc_minigames': 'Dolanan interaktif kaya Werewolf lan Truth or Dare kanggo grup.',
    'ai_persona': 'Studio Karakter AI',
    'desc_ai_persona': 'Karakter AI khusus kanggo WhatsApp.',
    'broadcast_manager': 'Pangurus Pesenan',
    'desc_broadcast_manager': 'Jadwalake pesen akeh lan kampanye.',
    'analytics_insights': 'Statistik & Wawasan',
    'desc_analytics_insights': 'Statistik bot lan panggunaan.',
    'ticketing_system': 'Sistem Tiket Langsung',
    'desc_ticketing_system': 'Pitulungan manungsa kanggo pangguna bot.',
    'app_integrations': 'Integrasi Aplikasi',
    'desc_app_integrations': 'Sambungake karo Webhook, Google Sheets, Discord & Slack.',

    'dashboard': 'Dasbor',
    'swap': 'Ganti',
    'earn': 'Oleh',
    'new': 'ANYAR',
    'settings': 'Setelan',
    'language': 'Basa',
    'appearance': 'Tampilan',
    'theme': 'Tema',
    'task_manager': 'Manajer Tugas',
    'monitor_processes': 'Pantau proses sing mbukak',
    'subscription': 'Langganan',
    'extend_plan': 'Perpanjang paket langganan panjenengan',
    'log_out': 'Metu',
    'sign_out': 'Metu saka sesi panjenengan',
    'app_store': 'Toko Aplikasi',
    'discover_modules': 'Temokake modul kanggo OS panjenengan.',
    'loading_catalog': 'Muat katalog...',
    'released': 'Dirilis',
    'installed': 'Kepasang',
    'get_install': 'Pasang',
    'installing': 'Masang...',
    'pinned_apps': 'APLIKASI TERSEMAT',
    'menu': 'MENU',
    'services_pricing': 'Layanan & Rego',
    'subscription_desc': 'Paket Langganan Wazle',
    'budget_adjustment_title': 'Badhe nyetel limit miturut anggaran panjenengan?',
    'budget_adjustment_btn': 'Pangaturan Anggaran',
    'adjust_package': 'Selarasake Paket',
    'response_slot': 'Slot Respon',
    'whatsapp_group': 'Grup WhatsApp',
    'support_service': 'Layanan Bantuan',
    'basic_service': 'Layanan Dhasar',
    'service_247': 'Layanan 24/7',
    'total_estimation': 'Total Estimasi',
    'order_via_wa': 'Pesen liwat WA',
    'storage_note': 'Panyimpenan / Cloud Storage mboten bakal ditambah / selaras layanan',
    'per_month': '/wulan',
    'plan_free_name': 'Gratis',
    'plan_basic_name': 'Dhasar',
    'plan_standard_name': 'Standar',
    'plan_premium_name': 'Premium',
    'feat_1_resp': '1 Respon',
    'feat_5_resp': '5 Respon',
    'feat_25_resp': '25 Respon',
    'feat_100_resp': '100 Respon',
    'feat_no_upload': 'Ora Ana Upload',
    'feat_500kb_upload': '500kb saben upload',
    'feat_5mb_upload': '5MB saben upload',
    'feat_15mb_upload': '15MB saben upload',
    'feat_few_services': 'Layanan Winates',
    'feat_50mb_storage': 'Maksimal 50MB Panyimpenan',
    'feat_500mb_storage': 'Maksimal 500MB Panyimpenan',
    'feat_1000mb_storage': 'Maksimal 1000MB Panyimpenan',
    'feat_1_group': '1 Grup',
    'feat_2_group': '2 Grup',
    'feat_5_group': '5 Grup',
    'feat_basic_support': 'Bantuan Dhasar',
    'feat_247_support': 'Bantuan 24/7',
    'current_subscription': 'Langganan Saiki',
    'plan': 'Paket',
    'days_left': 'Sisa Dina',
    'status': 'Status',
    'available_plans': 'Paket sing Kasedhiya',
    'popular': 'Populer',
    'days': 'dina',
    'Active': 'Aktif',
    'Inactive': 'Ora Aktif',
    'Free': 'Gratis',
    'Basic': 'Dhasar',
    'Standard': 'Standar',
    'Premium': 'Premium',
    'hi': 'HALO',
    'plan_active': 'Paket Aktif',
    'profile_information': 'Informasi Profil',
    'user_id': 'ID Pangguna',
    'connected_whatsapp': 'WhatsApp Nyambung',
    'valid_until': 'Baku Tekan',
    'protocols': 'Protokol',
    'access_modules': 'Akses kabeh modul sing dipasang',
    'control_center': 'Pusat Kontrol',
    'desc_control_center': 'Konfigurasi & logika bot',
    'file_explorer': 'File Explorer',
    'desc_file_explorer': 'Ngatur panyimpenan bot',
    'desc_task_manager': 'Ngawasi sumber daya sistem',
    'group_manager': 'Manajer Grup',
    'desc_group_manager': 'Ngatur grup sing nyambung',
    'auto_responders': 'Auto Responder',
    'used': 'digunakake',
    'create_new_response': 'Nggawe Respon Anyar',
    'keyword_label': 'Tembung Kunci (Keyword)',
    'example_ping': 'Conto: ping',
    'match_type_label': 'Jinis Cocog (Match Type)',
    'exact': 'Persis (Exact)',
    'contains': 'Ngemot (Contains)',
    'bot_reply_label': 'Wangsulan Bot',
    'example_pong': 'Conto: pong!',
    'saving': 'Nyimpen...',
    'save_auto_response': 'Simpen Auto Respon',
    'no_auto_responders': 'Urung ana auto responder.',
    'delete': 'Mbusak',
    'group_links': 'Tautan Grup',
    'your_tier_is': 'Paket panjenengan yaiku',
    'max': 'Maksimal',
    'groups_lowercase': 'grup',
    'whatsapp_group_prefix': 'Grup WhatsApp',
    'clear_link': 'Mbusak Tautan',
    'contact_staff_lock': 'Hubungi staf Wazle kanggo ngganti tautan iki.',
    'locked': 'Kunci',
    'save_links': 'Simpen Tautan',
    'server_reset': 'Server direset',
    'subscription_warning': 'Pènget: Langganan panjenengan gari {days} dina maneh!',
    'focus_music': 'Musik Fokus',
    'play': 'Muter',
    'pause': 'Mandheg',
    'engine_status': 'Status Mesin',
    'connecting': 'Nyambungake...',
    'offline': 'Offline',
    'start': 'Mulai',
    'stop': 'Mandheg',
    'scan_qr_desc': 'Scan QR Code iki nganggo<br/>WhatsApp ing HP target',
    'configurations': 'Konfigurasi',
    'anti_link': 'Anti-Link',
    'anti_link_desc': 'Otomatis mbusak tautan ing grup',
    'welcome_msg': 'Pesen Sambutan',
    'welcome_msg_desc': 'Sambut member anyar otomatis',
    'welcome_message': 'Pesen Sambutan',
    'premium_feature': 'Fitur Premium',
    'upgrade_custom_welcome': 'Upgrade paket kanggo kustomisasi pesen welcome.',
    'welcome_placeholder': 'Halo, sugeng rawuh ing grup...',
    'save_text': 'Simpen Teks'
  },
  su: {
    'bot_engine': 'Mesin Bot',
    'uptime': 'Waktos Aktip',
    'system_processes': 'Proses Sistem',
    'running': 'Leumpang',
    'idle': 'Cicing',
    'waiting': 'Ngadagoan',
    'status_active': 'Aktip',
    'status_disabled': 'Pareum',
    'trigger_syntax': 'Pemicu Sintaks',
    'trigger_placeholder': 'misal: !simpen',
    'action_output': 'Kaluaran Aksi',
    'save_media_cloud': 'Simpen Media ka Awan',
    'auto_forward': 'Teruskeun Otomatis',
    'trigger_webhook': 'Pemicu Webhook',
    'active_groups': 'Grup Aktip',
    'autosave': 'Simpen Otomatis',
    'applying_changes': 'Nerapkeun parobahan...',
    'storage': 'Panyimpenan',

    'uploading': 'Ngunggah...',
    'upload_file': 'Unggah Pail',
    'your_files': 'Pail Anjeun',
    'no_files_uploaded_yet': 'Teu acan aya pail anu diunggah',
    'hold_on_changes': 'Antosan, anjeun ngaganti hiji hal.',

    'version_info': 'v0.3 beta alpha',
    'macros_builder': 'Pangjieun Makro',
    'desc_macros_builder': 'Jieun parentah khusus sareng pemicu panyimpenan awan.',
    'minigames': 'Kaulinan Mini',
    'desc_minigames': 'Kaulinan interaktif sapertos Werewolf sareng Truth or Dare kanggo grup.',
    'ai_persona': 'Studio Karakter AI',
    'desc_ai_persona': 'Karakter AI khusus pikeun WhatsApp.',
    'broadcast_manager': 'Pangurus Bewara',
    'desc_broadcast_manager': 'Jadwalkeun pesen loba sareng kampanye.',
    'analytics_insights': 'Statistik & Wawasan',
    'desc_analytics_insights': 'Statistik bot sareng pamakean.',
    'ticketing_system': 'Sistem Tiket Langsung',
    'desc_ticketing_system': 'Pitulung jalma asli pikeun pamake bot.',
    'app_integrations': 'Integrasi Aplikasi',
    'desc_app_integrations': 'Sambungkeun jeung Webhook, Google Sheets, Discord & Slack.',

    'dashboard': 'Dasbor',
    'swap': 'Tuker',
    'earn': 'Kenging',
    'new': 'ANYAR',
    'settings': 'Setélan',
    'language': 'Basa',
    'appearance': 'Pintonan',
    'theme': 'Téma',
    'task_manager': 'Pangatur Tugas',
    'monitor_processes': 'Pantau prosés nu muka',
    'subscription': 'Langganan',
    'extend_plan': 'Papanjang pakét langganan anjeun',
    'log_out': 'Kaluar',
    'sign_out': 'Kaluar tina sési anjeun',
    'app_store': 'Toko Aplikasi',
    'discover_modules': 'Panggihan modul kanggo OS anjeun.',
    'loading_catalog': 'Ngamuat katalog...',
    'released': 'Dirilis',
    'installed': 'Dipasang',
    'get_install': 'Pasang',
    'installing': 'Masang...',
    'pinned_apps': 'APLIKASI DIPIN',
    'menu': 'MÉNU',
    'services_pricing': 'Layanan & Harga',
    'subscription_desc': 'Pakét Langganan Wazle',
    'budget_adjustment_title': 'Badé nyaluyukeun limit sareng anggaran anjeun?',
    'budget_adjustment_btn': 'Panyaluyuan Anggaran',
    'adjust_package': 'Saluyukeun Pakét',
    'response_slot': 'Slot Réspon',
    'whatsapp_group': 'Grup WhatsApp',
    'support_service': 'Layanan Bantos',
    'basic_service': 'Layanan Dasar',
    'service_247': 'Layanan 24/7',
    'total_estimation': 'Total Éstimasi',
    'order_via_wa': 'Pesen via WA',
    'storage_note': 'Panyimpenan / Cloud Storage moal ditambih / nyaluyukeun layanan',
    'per_month': '/sasih',
    'plan_free_name': 'Gratis',
    'plan_basic_name': 'Dasar',
    'plan_standard_name': 'Standar',
    'plan_premium_name': 'Prémium',
    'feat_1_resp': '1 Réspon',
    'feat_5_resp': '5 Réspon',
    'feat_25_resp': '25 Réspon',
    'feat_100_resp': '100 Réspon',
    'feat_no_upload': 'Teu Aya Upload',
    'feat_500kb_upload': '500kb per upload',
    'feat_5mb_upload': '5MB per upload',
    'feat_15mb_upload': '15MB per upload',
    'feat_few_services': 'Layanan Diwatesan',
    'feat_50mb_storage': 'Maksimal 50MB Panyimpenan',
    'feat_500mb_storage': 'Maksimal 500MB Panyimpenan',
    'feat_1000mb_storage': 'Maksimal 1000MB Panyimpenan',
    'feat_1_group': '1 Grup',
    'feat_2_group': '2 Grup',
    'feat_5_group': '5 Grup',
    'feat_basic_support': 'Bantos Dasar',
    'feat_247_support': 'Bantos 24/7',
    'current_subscription': 'Langganan Ayeuna',
    'plan': 'Pakét',
    'days_left': 'Sésa Dinten',
    'status': 'Status',
    'available_plans': 'Pakét nu Sadia',
    'popular': 'Populér',
    'days': 'dinten',
    'Active': 'Aktif',
    'Inactive': 'Teu Aktif',
    'Free': 'Gratis',
    'Basic': 'Dasar',
    'Standard': 'Standar',
    'Premium': 'Prémium',
    'hi': 'HALO',
    'plan_active': 'Pakét Aktif',
    'profile_information': 'Émbaran Profil',
    'user_id': 'ID Pamaké',
    'connected_whatsapp': 'WhatsApp Kahubung',
    'valid_until': 'Sah Dugi',
    'protocols': 'Protokol',
    'access_modules': 'Aksés sadaya modul nu dipasang',
    'control_center': 'Puseur Kontrol',
    'desc_control_center': 'Konfigurasi & logika bot',
    'file_explorer': 'File Explorer',
    'desc_file_explorer': 'Kelola panyimpenan bot',
    'desc_task_manager': 'Pantau sumber daya sistem',
    'group_manager': 'Pangatur Grup',
    'desc_group_manager': 'Kelola grup nu kahubung',
    'auto_responders': 'Auto Responder',
    'used': 'dipaké',
    'create_new_response': 'Jieun Réspon Anyar',
    'keyword_label': 'Kecap Kunci (Keyword)',
    'example_ping': 'Conto: ping',
    'match_type_label': 'Tipe Cocog (Match Type)',
    'exact': 'Pasti (Exact)',
    'contains': 'Ngandung (Contains)',
    'bot_reply_label': 'Waleran Bot',
    'example_pong': 'Conto: pong!',
    'saving': 'Nyimpen...',
    'save_auto_response': 'Simpen Auto Réspon',
    'no_auto_responders': 'Teu acan aya auto responder.',
    'delete': 'Hapus',
    'group_links': 'Tautan Grup',
    'your_tier_is': 'Pakét anjeun nyaéta',
    'max': 'Maksimal',
    'groups_lowercase': 'grup',
    'whatsapp_group_prefix': 'Grup WhatsApp',
    'clear_link': 'Hapus Tautan',
    'contact_staff_lock': 'Hubungi staf Wazle kanggo ngarobih tautan ieu.',
    'locked': 'Terkonci',
    'save_links': 'Simpen Tautan',
    'server_reset': 'Server direset',
    'subscription_warning': 'Pépéling: Langganan anjeun sésa {days} dinten deui!',
    'focus_music': 'Musik Fokus',
    'play': 'Puter',
    'pause': 'Reureuh',
    'engine_status': 'Status Mesin',
    'connecting': 'Nyambungkeun...',
    'offline': 'Offline',
    'start': 'Ngawitan',
    'stop': 'Eureun',
    'scan_qr_desc': 'Scan QR Code ieu nganggo<br/>WhatsApp di HP target',
    'configurations': 'Konfigurasi',
    'anti_link': 'Anti-Link',
    'anti_link_desc': 'Otomatis mupus tautan di grup',
    'welcome_msg': 'Pesen Pangbagea',
    'welcome_msg_desc': 'Ngabageakeun member anyar otomatis',
    'welcome_message': 'Pesen Pangbagea',
    'premium_feature': 'Fitur Premium',
    'upgrade_custom_welcome': 'Upgrade paket kanggo kustomisasi pesen welcome.',
    'welcome_placeholder': 'Halo, wilujeng sumping di grup...',
    'save_text': 'Simpen Teks'
  },
  th: {
    'bot_engine': 'เครื่องยนต์บอท',
    'uptime': 'เวลาทำงาน',
    'system_processes': 'กระบวนการระบบ',
    'running': 'กำลังทำงาน',
    'idle': 'ไม่ได้ใช้งาน',
    'waiting': 'กำลังรอ',
    'status_active': 'ทำงานอยู่',
    'status_disabled': 'ปิดใช้งาน',
    'trigger_syntax': 'คำสั่งเรียกใช้',
    'trigger_placeholder': 'เช่น !save',
    'action_output': 'การดำเนินการออก',
    'save_media_cloud': 'บันทึกสื่อลงคลาวด์',
    'auto_forward': 'ส่งต่ออัตโนมัติ',
    'trigger_webhook': 'เรียกใช้ Webhook',
    'active_groups': 'กลุ่มที่ทำงานอยู่',
    'autosave': 'บันทึกอัตโนมัติ',
    'applying_changes': 'กำลังใช้การเปลี่ยนแปลง...',
    'storage': 'พื้นที่จัดเก็บ',

    'uploading': 'กำลังอัปโหลด...',
    'upload_file': 'อัปโหลดไฟล์',
    'your_files': 'ไฟล์ของคุณ',
    'no_files_uploaded_yet': 'ยังไม่มีการอัปโหลดไฟล์',
    'hold_on_changes': 'รอก่อน คุณมีการเปลี่ยนแปลง',

    'version_info': 'v0.3 beta alpha',
    'macros_builder': 'ตัวสร้างมาโคร',
    'desc_macros_builder': 'สร้างคำสั่งที่กำหนดเองขั้นสูงและทริกเกอร์ที่เก็บข้อมูลบนคลาวด์',
    'minigames': 'มินิเกม',
    'desc_minigames': 'เกมอินเทอร์แอกทีฟเช่น Werewolf และ Truth or Dare สำหรับกลุ่ม',
    'ai_persona': 'สตูดิโอตัวละคร AI',
    'desc_ai_persona': 'บุคลิก AI ที่กำหนดเองสำหรับ WhatsApp',
    'broadcast_manager': 'จัดการการออกอากาศ',
    'desc_broadcast_manager': 'กำหนดเวลาข้อความจำนวนมากและแคมเปญ',
    'analytics_insights': 'การวิเคราะห์และข้อมูลเชิงลึก',
    'desc_analytics_insights': 'สถิติของบอทและตัวชี้วัดการใช้งาน',
    'ticketing_system': 'ระบบตั๋วแบบสด',
    'desc_ticketing_system': 'การโอนย้ายไปยังพนักงานและกล่องจดหมายสนับสนุนสำหรับผู้ใช้บอท',
    'app_integrations': 'การรวมแอป',
    'desc_app_integrations': 'เชื่อมต่อกับ Webhooks, Google Sheets, Discord & Slack',

    'dashboard': 'แผงควบคุม', 'swap': 'แลกเปลี่ยน', 'earn': 'รับ', 'new': 'ใหม่',
    'settings': 'การตั้งค่า', 'language': 'ภาษา', 'appearance': 'ลักษณะที่ปรากฏ', 'theme': 'ธีม',
    'task_manager': 'ตัวจัดการงาน', 'monitor_processes': 'ตรวจสอบหน้าต่างและกระบวนการ',
    'subscription': 'การสมัครสมาชิก', 'extend_plan': 'ต่ออายุแพ็กเกจของคุณ',
    'log_out': 'ออกจากระบบ', 'sign_out': 'ออกจากเซสชั่นของคุณ',
    'app_store': 'แอพสโตร์', 'discover_modules': 'ค้นพบและติดตั้งโมดูลสำหรับ OS ของคุณ',
    'loading_catalog': 'กำลังโหลดแคตตาล็อก...', 'released': 'เปิดตัว', 'installed': 'ติดตั้งแล้ว',
    'get_install': 'รับ / ติดตั้ง', 'installing': 'กำลังติดตั้ง...',
    'pinned_apps': 'แอพที่ปักหมุด', 'menu': 'เมนู',
    'services_pricing': 'บริการและราคา', 'subscription_desc': 'แพ็กเกจ Wazle',
    'budget_adjustment_title': 'ต้องการปรับขีดจำกัดตามงบประมาณของคุณหรือไม่?',
    'budget_adjustment_btn': 'การปรับงบประมาณ', 'adjust_package': 'ปรับแพ็กเกจ',
    'response_slot': 'ช่องตอบกลับ', 'whatsapp_group': 'กลุ่ม WhatsApp',
    'support_service': 'บริการสนับสนุน', 'basic_service': 'บริการพื้นฐาน', 'service_247': 'บริการ 24/7',
    'total_estimation': 'ประเมินรวม', 'order_via_wa': 'สั่งซื้อผ่าน WA',
    'storage_note': 'พื้นที่เก็บข้อมูลจะไม่ปรับตามบริการนี้', 'per_month': '/เดือน',
    'plan_free_name': 'ฟรี', 'plan_basic_name': 'พื้นฐาน', 'plan_standard_name': 'มาตรฐาน', 'plan_premium_name': 'พรีเมียม',
    'feat_1_resp': '1 การตอบกลับ', 'feat_5_resp': '5 การตอบกลับ', 'feat_25_resp': '25 การตอบกลับ', 'feat_100_resp': '100 การตอบกลับ',
    'feat_no_upload': 'ไม่มีการอัปโหลด', 'feat_500kb_upload': 'อัปโหลด 500kb ต่อไฟล์', 'feat_5mb_upload': 'อัปโหลด 5MB ต่อไฟล์', 'feat_15mb_upload': 'อัปโหลด 15MB ต่อไฟล์',
    'feat_few_services': 'บริการจำกัด', 'feat_50mb_storage': 'พื้นที่ 50MB', 'feat_500mb_storage': 'พื้นที่ 500MB', 'feat_1000mb_storage': 'พื้นที่ 1000MB',
    'feat_1_group': '1 กลุ่ม', 'feat_2_group': '2 กลุ่ม', 'feat_5_group': '5 กลุ่ม',
    'feat_basic_support': 'สนับสนุนพื้นฐาน', 'feat_247_support': 'สนับสนุน 24/7',
    'current_subscription': 'การสมัครสมาชิกปัจจุบัน', 'plan': 'แพ็กเกจ', 'days_left': 'วันคงเหลือ', 'status': 'สถานะ',
    'available_plans': 'แพ็กเกจที่มี', 'popular': 'ยอดนิยม', 'days': 'วัน', 'Active': 'ทำงาน', 'Inactive': 'ไม่ทำงาน',
    'Free': 'ฟรี', 'Basic': 'พื้นฐาน', 'Standard': 'มาตรฐาน', 'Premium': 'พรีเมียม', 'hi': 'สวัสดี',
    'plan_active': 'แพ็กเกจเปิดใช้งาน', 'profile_information': 'ข้อมูลโปรไฟล์', 'user_id': 'ไอดีผู้ใช้',
    'connected_whatsapp': 'WhatsApp ที่เชื่อมต่อ', 'valid_until': 'ใช้ได้จนถึง', 'protocols': 'โปรโตคอล',
    'access_modules': 'เข้าถึงโมดูลทั้งหมด', 'control_center': 'ศูนย์ควบคุม', 'desc_control_center': 'การตั้งค่า & ลอจิกของบอท',
    'file_explorer': 'จัดการไฟล์', 'desc_file_explorer': 'จัดการพื้นที่เก็บข้อมูล',
    'desc_task_manager': 'ตรวจสอบทรัพยากรระบบ', 'group_manager': 'จัดการกลุ่ม', 'desc_group_manager': 'จัดการกลุ่มที่เชื่อมต่อ',
    'auto_responders': 'ตอบกลับอัตโนมัติ', 'used': 'ใช้แล้ว', 'create_new_response': 'สร้างการตอบกลับใหม่',
    'keyword_label': 'คำหลัก (Keyword)', 'example_ping': 'ตัวอย่าง: ping', 'match_type_label': 'ประเภทการจับคู่ (Match Type)',
    'exact': 'ตรงกันพอดี (Exact)', 'contains': 'ประกอบด้วย (Contains)', 'bot_reply_label': 'การตอบกลับ',
    'example_pong': 'ตัวอย่าง: pong!', 'saving': 'กำลังบันทึก...', 'save_auto_response': 'บันทึกการตอบกลับ',
    'no_auto_responders': 'ไม่มีการตอบกลับอัตโนมัติ', 'delete': 'ลบ', 'group_links': 'ลิงก์กลุ่ม',
    'your_tier_is': 'ระดับของคุณคือ', 'max': 'สูงสุด', 'groups_lowercase': 'กลุ่ม', 'whatsapp_group_prefix': 'กลุ่ม WhatsApp',
    'clear_link': 'ล้างลิงก์', 'contact_staff_lock': 'ติดต่อทีมงานเพื่อเปลี่ยนลิงก์นี้', 'locked': 'ถูกล็อก',
    'save_links': 'บันทึกลิงก์', 'server_reset': 'รีเซ็ตเซิร์ฟเวอร์', 'subscription_warning': 'คำเตือน: การสมัครสมาชิกของคุณเหลืออีก {days} วัน!',
    'focus_music': 'เพลงโฟกัส', 'play': 'เล่น', 'pause': 'หยุดชั่วคราว', 'nav_home': 'หน้าหลัก', 'nav_pricing': 'ราคา', 'nav_download': 'ดาวน์โหลด',
    'pricing_title': 'ราคา', 'pricing_subtitle': 'ค้นหาแพ็กเกจที่เหมาะสมสำหรับการขยายธุรกิจของคุณ',
    'plan_free_desc': 'สำหรับผู้เริ่มต้นระบบอัตโนมัติ', 'plan_basic_desc': 'สำหรับฟรีแลนซ์และธุรกิจขนาดเล็ก',
    'plan_standard_desc': 'โซลูชั่นครบวงจรสำหรับทีมงานและร้านค้า', 'plan_premium_desc': 'ออกแบบสำหรับเอเจนซี่และธุรกิจขนาดใหญ่',
    'btn_choose_free': 'เลือก ฟรี', 'btn_choose_basic': 'เลือก พื้นฐาน', 'btn_choose_standard': 'เลือก มาตรฐาน', 'btn_choose_premium': 'เลือก พรีเมียม',
    'custom_billing_title': 'บิลที่กำหนดเอง', 'custom_billing_desc': 'ต้องการขีดจำกัดที่กำหนดเองหรือความปลอดภัยภายในองค์กร? เราช่วยคุณได้',
    'btn_contact_wa': 'ติดต่อเราทาง WhatsApp', 'footer_storage_note': 'หมายเหตุ: ข้อความจะไม่ถูกนับรวมในพื้นที่เก็บข้อมูล',
    'download_title': 'แอป Wazle', 'download_subtitle': 'รับประสบการณ์ที่ดีที่สุดผ่านแอปพลิเคชัน Android ของเรา',
    'download_btn': 'ดาวน์โหลด APK', 'download_preparing': 'กำลังเตรียม...', 'download_version': 'เวอร์ชัน: Beta v0.2 • ขนาด: 6MB',
    'download_note': 'หมายเหตุ: กรุณาเตรียมพื้นที่ว่างอย่างน้อย 30MB',
    'toast_welcome_saved': 'บันทึกเทมเพลตสำเร็จ!', 'toast_settings_updated': 'อัปเดตการตั้งค่า {label} แล้ว!',
    'toast_file_uploaded': 'อัปโหลดไฟล์สำเร็จ!', 'toast_file_deleted': 'ลบไฟล์สำเร็จ!', 'toast_group_saved': 'บันทึกกลุ่มสำเร็จ!',
    'toast_group_save_failed': 'บันทึกไม่สำเร็จ', 'toast_responder_updated': 'อัปเดตสำเร็จ!', 'toast_responder_added': 'เพิ่มสำเร็จ!',
    'toast_responder_deleted': 'ลบสำเร็จ!', 'toast_responder_failed': 'บันทึกไม่สำเร็จ',
    'engine_status': 'สถานะเครื่องยนต์',
    'connecting': 'กำลังเชื่อมต่อ...',
    'offline': 'ออฟไลน์',
    'start': 'เริ่ม',
    'stop': 'หยุด',
    'scan_qr_desc': 'สแกน QR Code นี้โดยใช้<br/>WhatsApp บนโทรศัพท์เป้าหมาย',
    'configurations': 'การตั้งค่า',
    'anti_link': 'ป้องกันลิงก์',
    'anti_link_desc': 'ลบลิงก์ในกลุ่มโดยอัตโนมัติ',
    'welcome_msg': 'ข้อความต้อนรับ',
    'welcome_msg_desc': 'ทักทายสมาชิกใหม่โดยอัตโนมัติ',
    'welcome_message': 'ข้อความต้อนรับ',
    'premium_feature': 'ฟีเจอร์พรีเมียม',
    'upgrade_custom_welcome': 'อัปเกรดแพ็กเกจเพื่อปรับแต่งข้อความต้อนรับ',
    'welcome_placeholder': 'สวัสดี ยินดีต้อนรับสู่กลุ่ม...',
    'save_text': 'บันทึกข้อความ'
  },
  zh: {
    'bot_engine': '机器人引擎',
    'uptime': '运行时间',
    'system_processes': '系统进程',
    'running': '运行中',
    'idle': '空闲',
    'waiting': '等待中',
    'status_active': '活动',
    'status_disabled': '已禁用',
    'trigger_syntax': '触发语法',
    'trigger_placeholder': '例如：!save',
    'action_output': '操作输出',
    'save_media_cloud': '将媒体保存到云端',
    'auto_forward': '自动转发',
    'trigger_webhook': '触发Webhook',
    'active_groups': '活跃群组',
    'autosave': '自动保存',
    'applying_changes': '正在应用更改...',
    'storage': '存储',

    'uploading': '正在上传...',
    'upload_file': '上传文件',
    'your_files': '您的文件',
    'no_files_uploaded_yet': '尚未上传任何文件',
    'hold_on_changes': '稍等，您已更改了一些内容。',

    'version_info': 'v0.3 beta alpha',
    'macros_builder': '宏生成器',
    'desc_macros_builder': '创建高级自定义命令和云存储触发器。',
    'minigames': '迷你游戏',
    'desc_minigames': '面向群组的互动游戏，如狼人杀和真心话大冒险。',
    'ai_persona': 'AI角色工作室',
    'desc_ai_persona': 'WhatsApp的自定义AI个性。',
    'broadcast_manager': '广播管理',
    'desc_broadcast_manager': '安排批量消息和活动。',
    'analytics_insights': '分析与洞察',
    'desc_analytics_insights': '机器人统计数据和使用指标。',
    'ticketing_system': '实时工单系统',
    'desc_ticketing_system': '为机器人用户提供人工交接和支持收件箱。',
    'app_integrations': '应用集成',
    'desc_app_integrations': '连接Webhook、Google Sheets、Discord和Slack。',

    'dashboard': '仪表板', 'swap': '交换', 'earn': '赚取', 'new': '新',
    'settings': '设置', 'language': '语言', 'appearance': '外观', 'theme': '主题',
    'task_manager': '任务管理器', 'monitor_processes': '监控进程与窗口',
    'subscription': '订阅', 'extend_plan': '延长您的订阅计划',
    'log_out': '登出', 'sign_out': '注销您的会话',
    'app_store': '应用商店', 'discover_modules': '发现并安装强大的模块',
    'loading_catalog': '正在加载目录...', 'released': '已发布', 'installed': '已安装',
    'get_install': '获取 / 安装', 'installing': '安装中...',
    'pinned_apps': '固定应用', 'menu': '菜单',
    'services_pricing': '服务与定价', 'subscription_desc': 'Wazle 订阅计划',
    'budget_adjustment_title': '想要根据预算调整限制？',
    'budget_adjustment_btn': '预算调整', 'adjust_package': '调整套餐',
    'response_slot': '响应槽位', 'whatsapp_group': 'WhatsApp 群组',
    'support_service': '支持服务', 'basic_service': '基础服务', 'service_247': '24/7 服务',
    'total_estimation': '总估算', 'order_via_wa': '通过 WhatsApp 订购',
    'storage_note': '存储空间不会根据此服务调整', 'per_month': '/月',
    'plan_free_name': '免费', 'plan_basic_name': '基础', 'plan_standard_name': '标准', 'plan_premium_name': '高级',
    'feat_1_resp': '1次回复', 'feat_5_resp': '5次回复', 'feat_25_resp': '25次回复', 'feat_100_resp': '100次回复',
    'feat_no_upload': '无文件上传', 'feat_500kb_upload': '每个文件 500kb', 'feat_5mb_upload': '每个文件 5MB', 'feat_15mb_upload': '每个文件 15MB',
    'feat_few_services': '有限服务', 'feat_50mb_storage': '50MB 存储', 'feat_500mb_storage': '500MB 存储', 'feat_1000mb_storage': '1000MB 存储',
    'feat_1_group': '1 个群组', 'feat_2_group': '2 个群组', 'feat_5_group': '5 个群组',
    'feat_basic_support': '基础支持', 'feat_247_support': '24/7 支持',
    'current_subscription': '当前订阅', 'plan': '计划', 'days_left': '剩余天数', 'status': '状态',
    'available_plans': '可选计划', 'popular': '热门', 'days': '天', 'Active': '活跃', 'Inactive': '未活跃',
    'Free': '免费', 'Basic': '基础', 'Standard': '标准', 'Premium': '高级', 'hi': '你好',
    'plan_active': '计划已激活', 'profile_information': '个人信息', 'user_id': '用户 ID',
    'connected_whatsapp': '已连接 WhatsApp', 'valid_until': '有效期至', 'protocols': '协议',
    'access_modules': '访问所有安装的模块', 'control_center': '控制中心', 'desc_control_center': '机器人配置与逻辑',
    'file_explorer': '文件管理器', 'desc_file_explorer': '管理机器人存储',
    'desc_task_manager': '监控系统资源', 'group_manager': '群组管理器', 'desc_group_manager': '管理已连接的群组',
    'auto_responders': '自动回复', 'used': '已用', 'create_new_response': '创建新回复',
    'keyword_label': '关键词 (Keyword)', 'example_ping': '示例: ping', 'match_type_label': '匹配类型 (Match Type)',
    'exact': '精确匹配 (Exact)', 'contains': '包含 (Contains)', 'bot_reply_label': '机器人回复',
    'example_pong': '示例: pong!', 'saving': '保存中...', 'save_auto_response': '保存自动回复',
    'no_auto_responders': '暂无自动回复。', 'delete': '删除', 'group_links': '群组链接',
    'your_tier_is': '您的等级是', 'max': '最大', 'groups_lowercase': '群组', 'whatsapp_group_prefix': 'WhatsApp 群组',
    'clear_link': '清除链接', 'contact_staff_lock': '请联系 Wazle 员工更改此链接。', 'locked': '已锁定',
    'save_links': '保存链接', 'server_reset': '服务器重置', 'subscription_warning': '警告：您的订阅仅剩 {days} 天！',
    'focus_music': '专注音乐', 'play': '播放', 'pause': '暂停', 'nav_home': '首页', 'nav_pricing': '定价', 'nav_download': '下载',
    'pricing_title': '定价', 'pricing_subtitle': '寻找适合您业务规模的完美计划。',
    'plan_free_desc': '适合刚开始自动化系统的创作者。', 'plan_basic_desc': '适合需要更多自由的自由职业者和小型企业。',
    'plan_standard_desc': '适用于团队运营和在线商店的完整解决方案。', 'plan_premium_desc': '专为代理商和大型企业设计。',
    'btn_choose_free': '选择免费', 'btn_choose_basic': '选择基础', 'btn_choose_standard': '选择标准', 'btn_choose_premium': '选择高级',
    'custom_billing_title': '定制计费', 'custom_billing_desc': '需要特殊限制、企业 ERP 集成或本地安全保障？我们为您量身定制。',
    'btn_contact_wa': '通过 WhatsApp 联系我们', 'footer_storage_note': '注意：上述存储容量仅适用于媒体上传。文本消息不占用存储空间。',
    'download_title': 'Wazle 应用程序', 'download_subtitle': '使用我们的原生 Android 应用获得最佳体验。',
    'download_btn': '下载 APK', 'download_preparing': '准备中...', 'download_version': '版本: Beta v0.2 • 大小: 6MB',
    'download_note': '注意：请至少腾出 30MB 存储空间。',
    'toast_welcome_saved': '欢迎模板保存成功！', 'toast_settings_updated': '{label} 设置已更新！',
    'toast_file_uploaded': '文件上传成功！', 'toast_file_deleted': '文件删除成功！', 'toast_group_saved': '群组数据保存成功！',
    'toast_group_save_failed': '保存失败。', 'toast_responder_updated': '自动回复更新成功！', 'toast_responder_added': '自动回复添加成功！',
    'toast_responder_deleted': '自动回复删除成功！', 'toast_responder_failed': '保存失败。',
    'engine_status': '引擎状态',
    'connecting': '连接中...',
    'offline': '离线',
    'start': '开始',
    'stop': '停止',
    'scan_qr_desc': '使用目标手机上的 WhatsApp<br/>扫描此二维码',
    'configurations': '配置',
    'anti_link': '防链接',
    'anti_link_desc': '自动删除群组中的链接',
    'welcome_msg': '欢迎信息',
    'welcome_msg_desc': '自动问候新成员',
    'welcome_message': '欢迎信息',
    'premium_feature': '高级功能',
    'upgrade_custom_welcome': '升级计划以自定义欢迎信息。',
    'welcome_placeholder': '你好，欢迎来到群组...',
    'save_text': '保存文本'
  },
  ko: {
    'bot_engine': '봇 엔진',
    'uptime': '가동 시간',
    'system_processes': '시스템 프로세스',
    'running': '실행 중',
    'idle': '유휴',
    'waiting': '대기 중',
    'status_active': '활성',
    'status_disabled': '비활성화됨',
    'trigger_syntax': '트리거 구문',
    'trigger_placeholder': '예: !save',
    'action_output': '작업 출력',
    'save_media_cloud': '클라우드에 미디어 저장',
    'auto_forward': '자동 전달',
    'trigger_webhook': '웹훅 트리거',
    'active_groups': '활성 그룹',
    'autosave': '자동 저장',
    'applying_changes': '변경 사항 적용 중...',
    'storage': '저장소',

    'uploading': '업로드 중...',
    'upload_file': '파일 업로드',
    'your_files': '내 파일',
    'no_files_uploaded_yet': '아직 업로드된 파일이 없습니다',
    'hold_on_changes': '잠깐만요, 변경된 사항이 있습니다.',

    'version_info': 'v0.3 beta alpha',
    'macros_builder': '매크로 빌더',
    'desc_macros_builder': '고급 사용자 지정 명령 및 클라우드 스토리지 트리거를 만듭니다.',
    'minigames': '미니 게임',
    'desc_minigames': '그룹을 위한 마피아 게임이나 진실 혹은 도전 같은 대화형 게임.',
    'ai_persona': 'AI 페르소나 스튜디오',
    'desc_ai_persona': 'WhatsApp용 맞춤형 AI 성격.',
    'broadcast_manager': '브로드캐스트 관리자',
    'desc_broadcast_manager': '대량 메시지 및 캠페인 예약.',
    'analytics_insights': '분석 및 인사이트',
    'desc_analytics_insights': '봇 통계 및 사용 지표.',
    'ticketing_system': '실시간 티켓팅 시스템',
    'desc_ticketing_system': '봇 사용자를 위한 인적 인수인계 및 지원 수신함.',
    'app_integrations': '앱 연동',
    'desc_app_integrations': '웹훅, Google Sheets, Discord 및 Slack과 연결하세요.',

    'dashboard': '대시보드', 'swap': '교환', 'earn': '수익', 'new': '신규',
    'settings': '설정', 'language': '언어', 'appearance': '모양', 'theme': '테마',
    'task_manager': '작업 관리자', 'monitor_processes': '프로세스 모니터링',
    'subscription': '구독', 'extend_plan': '구독 요금제 연장',
    'log_out': '로그아웃', 'sign_out': '세션에서 로그아웃',
    'app_store': '앱 스토어', 'discover_modules': '강력한 모듈 발견 및 설치',
    'loading_catalog': '카탈로그 로드 중...', 'released': '출시됨', 'installed': '설치됨',
    'get_install': '받기 / 설치', 'installing': '설치 중...',
    'pinned_apps': '고정된 앱', 'menu': '메뉴',
    'services_pricing': '서비스 및 가격', 'subscription_desc': 'Wazle 구독 요금제',
    'budget_adjustment_title': '예산에 맞춰 한도를 조정하시겠습니까?',
    'budget_adjustment_btn': '예산 조정', 'adjust_package': '패키지 조정',
    'response_slot': '응답 슬롯', 'whatsapp_group': 'WhatsApp 그룹',
    'support_service': '지원 서비스', 'basic_service': '기본 서비스', 'service_247': '24/7 서비스',
    'total_estimation': '총 예상치', 'order_via_wa': 'WA를 통해 주문',
    'storage_note': '저장소는 이 서비스에 의해 조정되지 않습니다', 'per_month': '/월',
    'plan_free_name': '무료', 'plan_basic_name': '기본', 'plan_standard_name': '표준', 'plan_premium_name': '프리미엄',
    'feat_1_resp': '1회 응답', 'feat_5_resp': '5회 응답', 'feat_25_resp': '25회 응답', 'feat_100_resp': '100회 응답',
    'feat_no_upload': '파일 업로드 없음', 'feat_500kb_upload': '파일당 500kb', 'feat_5mb_upload': '파일당 5MB', 'feat_15mb_upload': '파일당 15MB',
    'feat_few_services': '제한된 서비스', 'feat_50mb_storage': '최대 50MB 저장소', 'feat_500mb_storage': '최대 500MB 저장소', 'feat_1000mb_storage': '최대 1000MB 저장소',
    'feat_1_group': '1개 그룹', 'feat_2_group': '2개 그룹', 'feat_5_group': '5개 그룹',
    'feat_basic_support': '기본 지원', 'feat_247_support': '24/7 지원',
    'current_subscription': '현재 구독', 'plan': '요금제', 'days_left': '남은 일수', 'status': '상태',
    'available_plans': '사용 가능한 요금제', 'popular': '인기', 'days': '일', 'Active': '활성', 'Inactive': '비활성',
    'Free': '무료', 'Basic': '기본', 'Standard': '표준', 'Premium': '프리미엄', 'hi': '안녕하세요',
    'plan_active': '요금제 활성화됨', 'profile_information': '프로필 정보', 'user_id': '사용자 ID',
    'connected_whatsapp': '연결된 WhatsApp', 'valid_until': '유효 기간', 'protocols': '프로토콜',
    'access_modules': '설치된 모듈 액세스', 'control_center': '제어 센터', 'desc_control_center': '봇 구성 및 로직',
    'file_explorer': '파일 탐색기', 'desc_file_explorer': '봇 저장소 관리',
    'desc_task_manager': '시스템 리소스 모니터링', 'group_manager': '그룹 관리자', 'desc_group_manager': '연결된 그룹 관리',
    'auto_responders': '자동 응답기', 'used': '사용됨', 'create_new_response': '새 응답 만들기',
    'keyword_label': '키워드 (Keyword)', 'example_ping': '예: ping', 'match_type_label': '일치 유형 (Match Type)',
    'exact': '정확히 일치 (Exact)', 'contains': '포함 (Contains)', 'bot_reply_label': '봇 응답',
    'example_pong': '예: pong!', 'saving': '저장 중...', 'save_auto_response': '자동 응답 저장',
    'no_auto_responders': '자동 응답기가 없습니다.', 'delete': '삭제', 'group_links': '그룹 링크',
    'your_tier_is': '귀하의 등급은', 'max': '최대', 'groups_lowercase': '그룹', 'whatsapp_group_prefix': 'WhatsApp 그룹',
    'clear_link': '링크 지우기', 'contact_staff_lock': '링크를 변경하려면 직원에게 문의하세요.', 'locked': '잠김',
    'save_links': '링크 저장', 'server_reset': '서버 초기화', 'subscription_warning': '경고: 구독이 {days}일 남았습니다!',
    'focus_music': '포커스 음악', 'play': '재생', 'pause': '일시 정지', 'nav_home': '홈', 'nav_pricing': '가격', 'nav_download': '다운로드',
    'pricing_title': '가격', 'pricing_subtitle': '비즈니스 확장에 완벽한 요금제를 찾으세요.',
    'plan_free_desc': '자동화 시스템을 처음 시작하는 크리에이터를 위해.', 'plan_basic_desc': '더 많은 자유가 필요한 프리랜서 및 소규모 비즈니스를 위해.',
    'plan_standard_desc': '팀 운영 및 온라인 상점을 위한 완벽한 솔루션.', 'plan_premium_desc': '대규모 대행사 및 기업을 위해 설계되었습니다.',
    'btn_choose_free': '무료 선택', 'btn_choose_basic': '기본 선택', 'btn_choose_standard': '표준 선택', 'btn_choose_premium': '프리미엄 선택',
    'custom_billing_title': '맞춤형 청구', 'custom_billing_desc': '특수 한도, ERP 통합 또는 내부 보안이 필요하십니까? 맞춤형 아키텍처를 제공합니다.',
    'btn_contact_wa': 'WhatsApp으로 문의하기', 'footer_storage_note': '참고: 저장 용량은 미디어 업로드에만 적용됩니다. 텍스트 메시지는 저장 공간을 차지하지 않습니다.',
    'download_title': 'Wazle 앱', 'download_subtitle': '기본 Android 앱으로 최고의 경험을 얻으세요.',
    'download_btn': 'APK 다운로드', 'download_preparing': '준비 중...', 'download_version': '버전: Beta v0.2 • 크기: 6MB',
    'download_note': '참고: 최소 30MB의 여유 공간을 확보하세요.',
    'toast_welcome_saved': '환영 템플릿 저장 성공!', 'toast_settings_updated': '{label} 설정 업데이트됨!',
    'toast_file_uploaded': '파일 업로드 성공!', 'toast_file_deleted': '파일 삭제 성공!', 'toast_group_saved': '그룹 데이터 저장 성공!',
    'toast_group_save_failed': '저장 실패.', 'toast_responder_updated': '자동 응답기 업데이트 성공!', 'toast_responder_added': '자동 응답기 추가 성공!',
    'toast_responder_deleted': '자동 응답기 삭제 성공!', 'toast_responder_failed': '저장 실패.',
    'engine_status': '엔진 상태',
    'connecting': '연결 중...',
    'offline': '오프라인',
    'start': '시작',
    'stop': '중지',
    'scan_qr_desc': '대상 휴대폰의 WhatsApp을 사용하여<br/>이 QR 코드를 스캔하세요.',
    'configurations': '구성',
    'anti_link': '링크 방지',
    'anti_link_desc': '그룹의 링크를 자동으로 삭제합니다',
    'welcome_msg': '환영 메시지',
    'welcome_msg_desc': '새 회원에게 자동으로 인사',
    'welcome_message': '환영 메시지',
    'premium_feature': '프리미엄 기능',
    'upgrade_custom_welcome': '환영 메시지를 사용자 지정하려면 요금제를 업그레이드하세요.',
    'welcome_placeholder': '안녕하세요, 그룹에 오신 것을 환영합니다...',
    'save_text': '텍스트 저장'
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<LanguageCode>('en');

  useEffect(() => {
    const saved = localStorage.getItem('yay_language') as LanguageCode;
    if (saved && dictionaries[saved]) {
      setLanguage(saved);
    }
  }, []);

  const handleSetLanguage = (lang: LanguageCode) => {
    setLanguage(lang);
    localStorage.setItem('yay_language', lang);
  };

  const t = (key: string) => {
    return dictionaries[language]?.[key] || dictionaries['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
