'use client';
import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type LanguageCode = 'en' | 'id' | 'es' | 'ru' | 'zh' | 'ms' | 'fil' | 'ko' | 'ar' | 'jv' | 'su';

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const dictionaries: Record<LanguageCode, Record<string, string>> = {
  en: {
    'dashboard': 'Dashboard',
    'swap': 'Swap',
    'earn': 'Earn',
    'new': 'NEW',
    'settings': 'Settings',
    'language': 'Language',
    'appearance': 'Appearance',
    'theme': 'Theme',
    'task_manager': 'Task Manager',
    'monitor_processes': 'Monitor open windows & processes',
    'subscription': 'Subscription',
    'extend_plan': 'Extend your subscription plan',
    'log_out': 'Log out',
    'sign_out': 'Sign out of your session',
    'app_store': 'App Store',
    'discover_modules': 'Discover and install powerful modules for your OS.',
    'loading_catalog': 'Loading catalog...',
    'released': 'Released',
    'installed': 'Installed',
    'get_install': 'Get / Install',
    'installing': 'Installing...',
    'pinned_apps': 'PINNED APPS',
    'menu': 'MENU',
    'services_pricing': 'Services & Pricing',
    'subscription_desc': 'Wazle Subscription Plans',
    'budget_adjustment_title': 'Want to adjust limits to your budget?',
    'budget_adjustment_btn': 'Budget Adjustment',
    'adjust_package': 'Adjust Package',
    'response_slot': 'Response Slots',
    'whatsapp_group': 'WhatsApp Groups',
    'support_service': 'Support Service',
    'basic_service': 'Basic Service',
    'service_247': '24/7 Service',
    'total_estimation': 'Total Estimation',
    'order_via_wa': 'Order via WA',
    'storage_note': 'Storage / Cloud Storage will not be increased / adjusted by this service',
    'per_month': '/mo',
    'plan_free_name': 'Free',
    'plan_basic_name': 'Basic',
    'plan_standard_name': 'Standard',
    'plan_premium_name': 'Premium',
    'feat_1_resp': '1 Response',
    'feat_5_resp': '5 Responses',
    'feat_25_resp': '25 Responses',
    'feat_100_resp': '100 Responses',
    'feat_no_upload': 'No File Upload',
    'feat_500kb_upload': '500kb per file upload',
    'feat_5mb_upload': '5MB per file upload',
    'feat_15mb_upload': '15MB per file upload',
    'feat_few_services': 'Few Services',
    'feat_50mb_storage': '50MB Max Storage',
    'feat_500mb_storage': '500MB Max Storage',
    'feat_1000mb_storage': '1000MB Max Storage',
    'feat_1_group': '1 Group',
    'feat_2_group': '2 Groups',
    'feat_5_group': '5 Groups',
    'feat_basic_support': 'Basic Support',
    'feat_247_support': '24/7 Support',
    'current_subscription': 'Current Subscription',
    'plan': 'Plan',
    'days_left': 'Days Left',
    'status': 'Status',
    'available_plans': 'Available Plans',
    'popular': 'Popular',
    'days': 'days',
    'Active': 'Active',
    'Inactive': 'Inactive',
    'Free': 'Free',
    'Basic': 'Basic',
    'Standard': 'Standard',
    'Premium': 'Premium',
    'hi': 'HI',
    'plan_active': 'Plan Active',
    'profile_information': 'Profile Information',
    'user_id': 'User ID',
    'connected_whatsapp': 'Connected WhatsApp',
    'valid_until': 'Valid Until',
    'protocols': 'Protocols',
    'access_modules': 'Access all your installed modules',
    'control_center': 'Control Center',
    'desc_control_center': 'Bot configuration & logic',
    'file_explorer': 'File Explorer',
    'desc_file_explorer': 'Manage bot storage',
    'desc_task_manager': 'Monitor system resources',
    'group_manager': 'Group Manager',
    'desc_group_manager': 'Manage connected groups',
    'auto_responders': 'Auto Responders',
    'used': 'used',
    'create_new_response': 'Create New Response',
    'keyword_label': 'Keyword',
    'example_ping': 'Example: ping',
    'match_type_label': 'Match Type',
    'exact': 'Exact',
    'contains': 'Contains',
    'bot_reply_label': 'Bot Reply',
    'example_pong': 'Example: pong!',
    'saving': 'Saving...',
    'save_auto_response': 'Save Auto Response',
    'no_auto_responders': 'No auto responders yet.',
    'delete': 'Delete',
    'group_links': 'Group Links',
    'your_tier_is': 'Your tier is',
    'max': 'Max',
    'groups_lowercase': 'groups',
    'whatsapp_group_prefix': 'WhatsApp Group',
    'clear_link': 'Clear Link',
    'contact_staff_lock': 'Contact Wazle staff to change this link.',
    'locked': 'Locked',
    'save_links': 'Save Links'
  },
  id: {
    'dashboard': 'Dasbor',
    'swap': 'Tukar',
    'earn': 'Hasil',
    'new': 'BARU',
    'settings': 'Pengaturan',
    'language': 'Bahasa',
    'appearance': 'Tampilan',
    'theme': 'Tema',
    'task_manager': 'Manajer Tugas',
    'monitor_processes': 'Pantau proses & jendela terbuka',
    'subscription': 'Perpanjang Langganan',
    'extend_plan': 'Perpanjang paket langganan kamu',
    'log_out': 'Keluar',
    'sign_out': 'Keluar dari sesi kamu',
    'app_store': 'Toko Aplikasi',
    'discover_modules': 'Temukan dan pasang modul hebat untuk OS kamu.',
    'loading_catalog': 'Memuat katalog...',
    'released': 'Dirilis',
    'installed': 'Terpasang',
    'get_install': 'Pasang',
    'installing': 'Memasang...',
    'pinned_apps': 'APLIKASI TERSEMAT',
    'menu': 'MENU',
    'services_pricing': 'Layanan & Pricing',
    'subscription_desc': 'Paket Langganan Wazle',
    'budget_adjustment_title': 'Ingin menyesuaikan limit sesuai budget Anda?',
    'budget_adjustment_btn': 'Penyesuaian Anggaran',
    'adjust_package': 'Sesuaikan Paket',
    'response_slot': 'Slot Respon',
    'whatsapp_group': 'Grup WhatsApp',
    'support_service': 'Layanan Bantuan',
    'basic_service': 'Layanan Dasar',
    'service_247': 'Layanan 24/7',
    'total_estimation': 'Total Estimasi',
    'order_via_wa': 'Pesan via WA',
    'storage_note': 'Penyimpanan / Cloud Storage tidak akan ditambah / menyesuaikan layanan',
    'per_month': '/bln',
    'plan_free_name': 'Gratis',
    'plan_basic_name': 'Dasar',
    'plan_standard_name': 'Standar',
    'plan_premium_name': 'Premium',
    'feat_1_resp': '1 Respon',
    'feat_5_resp': '5 Respon',
    'feat_25_resp': '25 Respon',
    'feat_100_resp': '100 Respon',
    'feat_no_upload': 'Tanpa Upload File',
    'feat_500kb_upload': '500kb per file upload',
    'feat_5mb_upload': '5MB per file upload',
    'feat_15mb_upload': '15MB per file upload',
    'feat_few_services': 'Layanan Terbatas',
    'feat_50mb_storage': 'Maksimal 50MB Storage',
    'feat_500mb_storage': 'Maksimal 500MB Storage',
    'feat_1000mb_storage': 'Maksimal 1000MB Storage',
    'feat_1_group': '1 Grup',
    'feat_2_group': '2 Grup',
    'feat_5_group': '5 Grup',
    'feat_basic_support': 'Dukungan Dasar',
    'feat_247_support': 'Dukungan 24/7',
    'current_subscription': 'Langganan Saat Ini',
    'plan': 'Paket',
    'days_left': 'Sisa Hari',
    'status': 'Status',
    'available_plans': 'Paket Tersedia',
    'popular': 'Populer',
    'days': 'hari',
    'Active': 'Aktif',
    'Inactive': 'Tidak Aktif',
    'Free': 'Gratis',
    'Basic': 'Dasar',
    'Standard': 'Standar',
    'Premium': 'Premium',
    'hi': 'HALO',
    'plan_active': 'Paket Aktif',
    'profile_information': 'Informasi Profil',
    'user_id': 'ID Pengguna',
    'connected_whatsapp': 'WhatsApp Terhubung',
    'valid_until': 'Berlaku Hingga',
    'protocols': 'Protokol',
    'access_modules': 'Akses semua modul terpasang',
    'control_center': 'Pusat Kontrol',
    'desc_control_center': 'Konfigurasi & logika bot',
    'file_explorer': 'File Explorer',
    'desc_file_explorer': 'Kelola penyimpanan bot',
    'desc_task_manager': 'Pantau sumber daya sistem',
    'group_manager': 'Manajer Grup',
    'desc_group_manager': 'Kelola grup terhubung',
    'auto_responders': 'Auto Responder',
    'used': 'digunakan',
    'create_new_response': 'Buat Respon Baru',
    'keyword_label': 'Kata Kunci (Keyword)',
    'example_ping': 'Contoh: ping',
    'match_type_label': 'Tipe Kecocokan (Match Type)',
    'exact': 'Pasti (Exact)',
    'contains': 'Mengandung (Contains)',
    'bot_reply_label': 'Balasan Bot',
    'example_pong': 'Contoh: pong!',
    'saving': 'Menyimpan...',
    'save_auto_response': 'Simpan Auto Respon',
    'no_auto_responders': 'Belum ada auto responder.',
    'delete': 'Hapus',
    'group_links': 'Tautan Grup',
    'your_tier_is': 'Paket Anda adalah',
    'max': 'Maksimal',
    'groups_lowercase': 'grup',
    'whatsapp_group_prefix': 'Grup WhatsApp',
    'clear_link': 'Hapus Tautan',
    'contact_staff_lock': 'Hubungi staf Wazle untuk mengubah tautan ini.',
    'locked': 'Terkunci',
    'save_links': 'Simpan Tautan'
  },
  jv: {
    'dashboard': 'Dasbor',
    'swap': 'Ganti',
    'earn': 'Oleh',
    'new': 'ANYAR',
    'settings': 'Setelan',
    'language': 'Basa',
    'appearance': 'Tampilan',
    'theme': 'Tema',
    'task_manager': 'Manajer Tugas',
    'monitor_processes': 'Pantau proses sing mbukak',
    'subscription': 'Langganan',
    'extend_plan': 'Perpanjang paket langganan panjenengan',
    'log_out': 'Metu',
    'sign_out': 'Metu saka sesi panjenengan',
    'app_store': 'Toko Aplikasi',
    'discover_modules': 'Temokake modul kanggo OS panjenengan.',
    'loading_catalog': 'Muat katalog...',
    'released': 'Dirilis',
    'installed': 'Kepasang',
    'get_install': 'Pasang',
    'installing': 'Masang...',
    'pinned_apps': 'APLIKASI TERSEMAT',
    'menu': 'MENU',
    'services_pricing': 'Layanan & Rego',
    'subscription_desc': 'Paket Langganan Wazle',
    'budget_adjustment_title': 'Badhe nyetel limit miturut anggaran panjenengan?',
    'budget_adjustment_btn': 'Pangaturan Anggaran',
    'adjust_package': 'Selarasake Paket',
    'response_slot': 'Slot Respon',
    'whatsapp_group': 'Grup WhatsApp',
    'support_service': 'Layanan Bantuan',
    'basic_service': 'Layanan Dhasar',
    'service_247': 'Layanan 24/7',
    'total_estimation': 'Total Estimasi',
    'order_via_wa': 'Pesen liwat WA',
    'storage_note': 'Panyimpenan / Cloud Storage mboten bakal ditambah / selaras layanan',
    'per_month': '/wulan',
    'plan_free_name': 'Gratis',
    'plan_basic_name': 'Dhasar',
    'plan_standard_name': 'Standar',
    'plan_premium_name': 'Premium',
    'feat_1_resp': '1 Respon',
    'feat_5_resp': '5 Respon',
    'feat_25_resp': '25 Respon',
    'feat_100_resp': '100 Respon',
    'feat_no_upload': 'Ora Ana Upload',
    'feat_500kb_upload': '500kb saben upload',
    'feat_5mb_upload': '5MB saben upload',
    'feat_15mb_upload': '15MB saben upload',
    'feat_few_services': 'Layanan Winates',
    'feat_50mb_storage': 'Maksimal 50MB Panyimpenan',
    'feat_500mb_storage': 'Maksimal 500MB Panyimpenan',
    'feat_1000mb_storage': 'Maksimal 1000MB Panyimpenan',
    'feat_1_group': '1 Grup',
    'feat_2_group': '2 Grup',
    'feat_5_group': '5 Grup',
    'feat_basic_support': 'Bantuan Dhasar',
    'feat_247_support': 'Bantuan 24/7',
    'current_subscription': 'Langganan Saiki',
    'plan': 'Paket',
    'days_left': 'Sisa Dina',
    'status': 'Status',
    'available_plans': 'Paket sing Kasedhiya',
    'popular': 'Populer',
    'days': 'dina',
    'Active': 'Aktif',
    'Inactive': 'Ora Aktif',
    'Free': 'Gratis',
    'Basic': 'Dhasar',
    'Standard': 'Standar',
    'Premium': 'Premium',
    'hi': 'HALO',
    'plan_active': 'Paket Aktif',
    'profile_information': 'Informasi Profil',
    'user_id': 'ID Pangguna',
    'connected_whatsapp': 'WhatsApp Nyambung',
    'valid_until': 'Baku Tekan',
    'protocols': 'Protokol',
    'access_modules': 'Akses kabeh modul sing dipasang',
    'control_center': 'Pusat Kontrol',
    'desc_control_center': 'Konfigurasi & logika bot',
    'file_explorer': 'File Explorer',
    'desc_file_explorer': 'Ngatur panyimpenan bot',
    'desc_task_manager': 'Ngawasi sumber daya sistem',
    'group_manager': 'Manajer Grup',
    'desc_group_manager': 'Ngatur grup sing nyambung',
    'auto_responders': 'Auto Responder',
    'used': 'digunakake',
    'create_new_response': 'Nggawe Respon Anyar',
    'keyword_label': 'Tembung Kunci (Keyword)',
    'example_ping': 'Conto: ping',
    'match_type_label': 'Jinis Cocog (Match Type)',
    'exact': 'Persis (Exact)',
    'contains': 'Ngemot (Contains)',
    'bot_reply_label': 'Wangsulan Bot',
    'example_pong': 'Conto: pong!',
    'saving': 'Nyimpen...',
    'save_auto_response': 'Simpen Auto Respon',
    'no_auto_responders': 'Urung ana auto responder.',
    'delete': 'Mbusak',
    'group_links': 'Tautan Grup',
    'your_tier_is': 'Paket panjenengan yaiku',
    'max': 'Maksimal',
    'groups_lowercase': 'grup',
    'whatsapp_group_prefix': 'Grup WhatsApp',
    'clear_link': 'Mbusak Tautan',
    'contact_staff_lock': 'Hubungi staf Wazle kanggo ngganti tautan iki.',
    'locked': 'Kunci',
    'save_links': 'Simpen Tautan'
  },
  su: {
    'dashboard': 'Dasbor',
    'swap': 'Tuker',
    'earn': 'Kenging',
    'new': 'ANYAR',
    'settings': 'Setélan',
    'language': 'Basa',
    'appearance': 'Pintonan',
    'theme': 'Téma',
    'task_manager': 'Pangatur Tugas',
    'monitor_processes': 'Pantau prosés nu muka',
    'subscription': 'Langganan',
    'extend_plan': 'Papanjang pakét langganan anjeun',
    'log_out': 'Kaluar',
    'sign_out': 'Kaluar tina sési anjeun',
    'app_store': 'Toko Aplikasi',
    'discover_modules': 'Panggihan modul kanggo OS anjeun.',
    'loading_catalog': 'Ngamuat katalog...',
    'released': 'Dirilis',
    'installed': 'Dipasang',
    'get_install': 'Pasang',
    'installing': 'Masang...',
    'pinned_apps': 'APLIKASI DIPIN',
    'menu': 'MÉNU',
    'services_pricing': 'Layanan & Harga',
    'subscription_desc': 'Pakét Langganan Wazle',
    'budget_adjustment_title': 'Badé nyaluyukeun limit sareng anggaran anjeun?',
    'budget_adjustment_btn': 'Panyaluyuan Anggaran',
    'adjust_package': 'Saluyukeun Pakét',
    'response_slot': 'Slot Réspon',
    'whatsapp_group': 'Grup WhatsApp',
    'support_service': 'Layanan Bantos',
    'basic_service': 'Layanan Dasar',
    'service_247': 'Layanan 24/7',
    'total_estimation': 'Total Éstimasi',
    'order_via_wa': 'Pesen via WA',
    'storage_note': 'Panyimpenan / Cloud Storage moal ditambih / nyaluyukeun layanan',
    'per_month': '/sasih',
    'plan_free_name': 'Gratis',
    'plan_basic_name': 'Dasar',
    'plan_standard_name': 'Standar',
    'plan_premium_name': 'Prémium',
    'feat_1_resp': '1 Réspon',
    'feat_5_resp': '5 Réspon',
    'feat_25_resp': '25 Réspon',
    'feat_100_resp': '100 Réspon',
    'feat_no_upload': 'Teu Aya Upload',
    'feat_500kb_upload': '500kb per upload',
    'feat_5mb_upload': '5MB per upload',
    'feat_15mb_upload': '15MB per upload',
    'feat_few_services': 'Layanan Diwatesan',
    'feat_50mb_storage': 'Maksimal 50MB Panyimpenan',
    'feat_500mb_storage': 'Maksimal 500MB Panyimpenan',
    'feat_1000mb_storage': 'Maksimal 1000MB Panyimpenan',
    'feat_1_group': '1 Grup',
    'feat_2_group': '2 Grup',
    'feat_5_group': '5 Grup',
    'feat_basic_support': 'Bantos Dasar',
    'feat_247_support': 'Bantos 24/7',
    'current_subscription': 'Langganan Ayeuna',
    'plan': 'Pakét',
    'days_left': 'Sésa Dinten',
    'status': 'Status',
    'available_plans': 'Pakét nu Sadia',
    'popular': 'Populér',
    'days': 'dinten',
    'Active': 'Aktif',
    'Inactive': 'Teu Aktif',
    'Free': 'Gratis',
    'Basic': 'Dasar',
    'Standard': 'Standar',
    'Premium': 'Prémium',
    'hi': 'HALO',
    'plan_active': 'Pakét Aktif',
    'profile_information': 'Émbaran Profil',
    'user_id': 'ID Pamaké',
    'connected_whatsapp': 'WhatsApp Kahubung',
    'valid_until': 'Sah Dugi',
    'protocols': 'Protokol',
    'access_modules': 'Aksés sadaya modul nu dipasang',
    'control_center': 'Puseur Kontrol',
    'desc_control_center': 'Konfigurasi & logika bot',
    'file_explorer': 'File Explorer',
    'desc_file_explorer': 'Kelola panyimpenan bot',
    'desc_task_manager': 'Pantau sumber daya sistem',
    'group_manager': 'Pangatur Grup',
    'desc_group_manager': 'Kelola grup nu kahubung',
    'auto_responders': 'Auto Responder',
    'used': 'dipaké',
    'create_new_response': 'Jieun Réspon Anyar',
    'keyword_label': 'Kecap Kunci (Keyword)',
    'example_ping': 'Conto: ping',
    'match_type_label': 'Tipe Cocog (Match Type)',
    'exact': 'Pasti (Exact)',
    'contains': 'Ngandung (Contains)',
    'bot_reply_label': 'Waleran Bot',
    'example_pong': 'Conto: pong!',
    'saving': 'Nyimpen...',
    'save_auto_response': 'Simpen Auto Réspon',
    'no_auto_responders': 'Teu acan aya auto responder.',
    'delete': 'Hapus',
    'group_links': 'Tautan Grup',
    'your_tier_is': 'Pakét anjeun nyaéta',
    'max': 'Maksimal',
    'groups_lowercase': 'grup',
    'whatsapp_group_prefix': 'Grup WhatsApp',
    'clear_link': 'Hapus Tautan',
    'contact_staff_lock': 'Hubungi staf Wazle kanggo ngarobih tautan ieu.',
    'locked': 'Terkonci',
    'save_links': 'Simpen Tautan'
  },
  es: { }, ru: { }, zh: { }, ms: { }, fil: { }, ko: { }, ar: { }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<LanguageCode>('en');

  useEffect(() => {
    const saved = localStorage.getItem('yay_language') as LanguageCode;
    if (saved && dictionaries[saved]) {
      setLanguage(saved);
    }
  }, []);

  const handleSetLanguage = (lang: LanguageCode) => {
    setLanguage(lang);
    localStorage.setItem('yay_language', lang);
  };

  const t = (key: string) => {
    return dictionaries[language]?.[key] || dictionaries['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
